# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/IVA/Research/int_cusum_multi_stream/int_cusum_multi_stream.srcs/sources_1/ip/fifo16x32/fifo16x32.xci
# IP: The module: 'fifo16x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/int_cusum_multi_stream/int_cusum_multi_stream.gen/sources_1/ip/fifo16x32/fifo16x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo16x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/IVA/Research/int_cusum_multi_stream/int_cusum_multi_stream.srcs/sources_1/ip/fifo16x32/fifo16x32.xci
# IP: The module: 'fifo16x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/IVA/Research/int_cusum_multi_stream/int_cusum_multi_stream.gen/sources_1/ip/fifo16x32/fifo16x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo16x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
